### ISSUE TITLE
JAIST東京 授業カレンダー登録 2022年度版のご相談

### ISSUE THREAD

**Issue by moruku36** [johntronik/jaist-tokyo-lecture#1]
2021年入学　JAIST東京社会人校のmoruku36と申します。

JAIST東京 授業カレンダーのメンテナンスありがとうございます。
去年一年間利用させていただきました。

4月から新学期ということで、2022年度版の授業カレンダーを作成したいのですが、
2022年度版CSVファイルをお渡しすればアップデートいただけますでしょうか？

以上、よろしくお願いいたします。

**Comment by johntronik** [comment]
ご連絡ありがとうございます！更新しますね！

**Comment by johntronik** [comment]
@moruku36 
こちらでデータ更新しました！
簡単なチェックしかしてないですが動いていると思いますー

**Comment by moruku36** [comment]
@johntronik 
早速の更新ありがとうございます！！
2022年度版の日程で動作してることを確認しました。

メンテナンスありがとうございます。非常に助かります。
